spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/students_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Use `create`, `create-drop`, `validate`, or `none` depending on need
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      platform: postgres
      schema-locations: classpath:schema-postgres.sql
      data-locations: classpath:data-postgres.sql

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        orm: DEBUG
        transaction: DEBUG
        security: INFO
