# Logging
logging:
  level:
    org:
      springframework:
        security: DEBUG
        jdbc: DEBUG
        orm: DEBUG
        transaction: DEBUG
# h2
spring:
  jpa:
    hibernate:
      ddl-auto: none  # Set to `none`for using SQL scripts to create tables manually
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    generate-unique-name: false
    name: studentsdb
    url: jdbc:h2:mem:studentsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath:schema-h2.sql
      data-locations: classpath:data-h2.sql