--INSERT INTO students (email, name, password, active) VALUES
--('admin@example.com', 'Admin', 'admin', TRUE),
--('alice-postgres@example.com', 'Alice Johnson', 'passAlice123', TRUE),
--('bob@example.com', 'Bob Smith', 'bobSecure456', TRUE),
--('carol@example.com', 'Carol White', 'carolPwd789', TRUE),
--('david@example.com', 'David Brown', 'dav!dPwd321', TRUE),
--('eva@example.com', 'Eva Green', 'evaSecret987', TRUE),
--('frank@example.com', 'Frank Harris', 'fr4nkStrongPwd', TRUE),
--('grace@example.com', 'Grace Lee', 'gracePwd432', TRUE),
--('henry@example.com', 'Henry Adams', 'h3nrySafePass', TRUE),
--('irene@example.com', 'Irene Lewis', 'iren3TopPwd', TRUE),
--('jack@example.com', 'Jack Walker', 'jackPwd654', TRUE),
--('test@example.com', 'Test', 'test', TRUE);
--
---- admin@example.com
--INSERT INTO student_roles (email, roles) VALUES
--('admin@example.com', 'STUDENT'),
--('admin@example.com', 'TEACHER'),
--('admin@example.com', 'ADMIN');
--
---- alice@example.com
--INSERT INTO STUDENT_ROLES (email, roles) VALUES ('alice-postgres@example.com', 'STUDENT');
--
---- bob@example.com
--INSERT INTO STUDENT_ROLES (email, roles) VALUES ('bob@example.com', 'STUDENT');
--
---- carol@example.com
--INSERT INTO STUDENT_ROLES (email, roles) VALUES ('carol@example.com', 'STUDENT');
--
---- david@example.com
--INSERT INTO STUDENT_ROLES (email, roles) VALUES ('david@example.com', 'STUDENT');
--
---- eva@example.com
--INSERT INTO STUDENT_ROLES (email, roles) VALUES ('eva@example.com', 'STUDENT');
--
---- frank@example.com
--INSERT INTO STUDENT_ROLES (email, roles) VALUES ('frank@example.com', 'STUDENT');
--
---- grace@example.com
--INSERT INTO STUDENT_ROLES (email, roles) VALUES ('grace@example.com', 'STUDENT');
--
---- henry@example.com
--INSERT INTO STUDENT_ROLES (email, roles) VALUES ('henry@example.com', 'STUDENT');
--
---- irene@example.com
--INSERT INTO STUDENT_ROLES (email, roles) VALUES ('irene@example.com', 'STUDENT');
--
---- jack@example.com
--INSERT INTO STUDENT_ROLES (email, roles) VALUES ('jack@example.com', 'STUDENT');
--
---- test@example.com
--INSERT INTO STUDENT_ROLES (email, roles) VALUES
--('test@example.com', 'STUDENT'),
--('test@example.com', 'ADMIN');
