name: Gradle CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Check Java version
        run: java -version

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew
        working-directory: students

      - name: Build with Gradle
        run: ./gradlew build --stacktrace
        working-directory: students
